name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Flutter Web & generate web platform
        working-directory: app
        run: |
          flutter config --enable-web
          flutter create . --platforms web --project-name rayando
          git checkout -- web/index.html || true

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: app
        run: flutter build web --release --base-href "/juego-pintar-multiplataforma/" --pwa-strategy=none

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
